# Generated by Django 3.1.7 on 2021-03-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='In INR', max_digits=65, null=True),
        ),
        migrations.AddField(
            model_name='registrations',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='In INR', max_digits=65, null=True),
        ),
    ]
