# Generated by Django 3.1.7 on 2021-03-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210324_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='importexportdata',
            name='csv_file',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
